version: '3'

volumes: 
  db-data:
    external: false
  es-data:
    external: false

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./sql:/dumps

  adminer:
    image: adminer
    ports:
      - 8080:8080

  web:
    build: chat-module/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    environment: 
      - ELASTICSEARCH_URL=elasticsearch:9200
    ports: 
      - 3001:3001
    # volumes:
    #   - ./chat-module:/app
    links: 
      - db
      - elasticsearch
      - redis

  web2:
    build: chat-module/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
    environment: 
      - ELASTICSEARCH_URL=elasticsearch:9200
    ports: 
      - 3002:3002
    # volumes:
    #   - ./chat-module:/app
    links: 
      - db
      - elasticsearch
      - redis
  
  sidekiq:
    build: chat-module/
    command: bundle exec sidekiq -d -L log/sidekiq.log
    depends_on:
      - redis
    # volumes:
    #   - ./chat-module:/app
    links: 
      - db
      - redis
  
  elasticsearch:
    image: elasticsearch:7.4.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 3000
      nofile: 65536
      memlock: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  
  nginx:
    image: nginx
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 3000:3000
    links:
      - web
      - web2
  
  redis:
    image: "redis:alpine"
    ports: 
      - 6379:6379
  
  cli:
    build: client/
    command: bash -c "go build"
    volumes: 
      - ./client/:/go/src/client
    environment: 
      - BASE_URL=nginx:3000

